FROM ubuntu:23.04

# Update the package lists and install necessary packages
RUN apt-get update \
    && apt-get install -y apt-cacher-ng avahi-daemon \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 3142

# Start the MariaDB service when the container is run
CMD ["mysqld"]
