# from: https://github.com/razinj/docker-custom-apt-cacher-ng

- name: Create data directory
  ansible.builtin.file:
    path: "{{ cache_data_dir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  become: true

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: Containerfile
    dest: "{{ container_home }}/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'

- name: Build a basic OCI image
  containers.podman.podman_image:
    name: "{{ container_name }}"
    path: "{{ container_home }}"

- name: Run apt-cacher-ng container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ container_name }}"
    state: started
    ports:
        - "3142:3142"
    volume: "{{ cache_data_dir }}:/var/cache/apt-cacher-ng"

# Run on all interfaces:
#podman run -d -p 3142:3142 -v ~/.uni/data/apt-cacher-ng:/var/cache/apt-cacher-ng --name apt-cacher-ng apt-cacher-ng.server