# https://help.ubuntu.com/community/Apt-Cacher%20NG#Client_setup

- name: Template apt.conf.d proxy
  ansible.builtin.template:
    src: proxy.j2
    dest: /etc/apt/apt.conf.d/proxy
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: apt update cache
