# https://wiki.debian.org/AptCacherNg

- name: AptCacherNg Client
  ansible.builtin.apt:
    pkg:
      - squid-deb-proxy-client
      - auto-apt-proxy
    update_cache: true
  become: true
  when: configuration == "automatic"
  notify:
  - Fix, 403 CONNECT denied error
  - Update cache

- include_tasks: backup.yml

# - include_tasks: 'vagrant.yml'

- name: Force flush handlers
  ansible.builtin.meta: flush_handlers