- name: Apt.conf on Vagrant
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf
    regexp: '^Acquire::http::Proxy'
    line: 'Acquire::http::Proxy "http://{{ aptcacherng_ip }}:3142";'
    create: true
    mode: "0600"
  become: true
  notify:
  - Fix, 403 CONNECT denied error
  - apt update cache

- name: Force flush handlers
  ansible.builtin.meta: flush_handlers