Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
