Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # config.vm.network "private_network", type: "dhcp"

  # config.vm.provider :libvirt do |libvirt|
  #   libvirt.graphics_port = 5901
  #   libvirt.graphics_ip = '0.0.0.0'
  #   libvirt.video_type = 'qxl'
  # end


  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
