Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2304" #ubuntu2310

  config.vm.define "apt-cacher.test"

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
