- name: Update web servers
  hosts: default
  remote_user: vagrant

  tasks:
    - name: AptCacherNg Client
      ansible.builtin.apt:
        pkg:
          - squid-deb-proxy-client
          - auto-apt-proxy
      become: true

    - name: Apt.conf
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf
        regexp: '^Acquire::http::Proxy'
        line: Acquire::http::Proxy "http://172.28.128.1:3142";
        create: true
        mode: "0600"
      become: true

    # Solution: https://forum.qubes-os.org/t/trouble-setting-up-apt-cacher-ng/12223
    - name: Fix - 403 CONNECT denied error
      ansible.builtin.shell: "{{ item }}"
      loop:
        - "sed -i 's#https://#http://HTTPS///#g' /etc/apt/sources.list"
        - "sed -i 's#https://#http://HTTPS///#g' /etc/apt/sources.list.d/*.list"
      become: true
      failed_when: false
