# https://wiki.debian.org/AptCacherNg

- name: install AptCacherNg
  ansible.builtin.apt:
    pkg:
    - apt-cacher-ng
  become: true

- name: install Avahi
  ansible.builtin.apt:
    pkg:
    - avahi-daemon
  become: true
  when: Avahi

- name: Enable AptCacherNg
  ansible.builtin.systemd:
    name: apt-cacher-ng #.service
    state: started
    enabled: true