- name: AptCacherNg Server
  hosts: localhost
  tags: [ server ]
  roles:
  - AptCacherNg/Server


- name: AptCacherNg Clean cache
  hosts: localhost
  tags: [ clean ]
  roles:
  - AptCacherNg/clean/server


  # vars:
  #   ansible_become_password: u
