- name: AptCacherNg Server
  hosts: localhost
  tags: [ server ]
  roles:
  - AptCacherNg/Server

- hosts: localhost
  tags: [ client ]
  vars:
    aptcacher_server: 10.0.1.4
  roles:
  - AptCacherNg/Client

- hosts: maas
  tags: [ maas ]
  vars:
    aptcacher_server: 10.0.1.4
  roles:
  - AptCacherNg/MAAS/client


- name: AptCacherNg Clean cache
  hosts: localhost
  tags: [ clean ]
  roles:
  - AptCacherNg/clean/server


  # vars:
  #   ansible_become_password: u
