- hosts: apt_cache_server #, localhost
  roles:
  - UniInc.AptCacherNg-Server-inContainer


- hosts: node #, apt_cacher_client #, localhost
  roles:
  - ansible-role-AptCacherNg-Client
#  - UniInc.AptCacherNg-Client
